# Generated by Django 4.1.4 on 2022-12-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziva_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_name', models.CharField(blank=True, max_length=50, null=True)),
                ('store_file', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('legal_name', models.CharField(blank=True, max_length=50, null=True)),
                ('select_region', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_No', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_attach', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('pan_card', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_attach', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('food_licence', models.CharField(blank=True, max_length=50, null=True)),
                ('food_attach', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('trade_licence', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_attach', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('store_location', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.ImageField(max_length=10, upload_to='')),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.ImageField(max_length=10, upload_to='')),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storelist',
            name='food_licence',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='storelist',
            name='gst_No',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='storelist',
            name='trade_licence',
            field=models.CharField(max_length=10),
        ),
    ]
